In [3]:
import pandas as pd

In [4]:
d1 = pd.read_csv('dbvpa_01_all.csv').set_index(['times', 'senders']).sort_index()
d2 = pd.read_csv('dbvpa_02_all.csv').set_index(['times', 'senders']).sort_index()

In [5]:
dd = d2 - d1

In [6]:
bad_targets = list(dd.loc[dd.I_syn_ex != 0].index.get_level_values('senders'))

In [7]:
sources = [10, 49, 41, 41, 9, 44, 19, 46, 9, 25, 11, 33, 46, 37,
               36, 27, 45, 29, 15, 27, 21, 50, 27, 38, 3, 5, 38, 3,
               41, 49, 42, 37, 36, 45, 5, 3, 21, 29, 9, 30, 34, 40,
               35, 44, 41, 48, 44, 27, 36, 47]

In [8]:
tgt_2_src = {i+1: s for i, s in enumerate(sources)}

In [9]:
bad_sources = {tgt_2_src[t] for t in bad_targets}

In [10]:
bad_sources

{10, 30, 34, 36, 38, 40, 42, 44, 46, 48, 50}

In [11]:
good_sources = set(range(1, 51))-bad_sources

In [12]:
bad_conns = [(s, i+1) for i, s in enumerate(sources) if i+1 in bad_targets]
good_conns = [(s, i+1) for i, s in enumerate(sources) if i+1 not in bad_targets]

In [13]:
bad = pd.DataFrame(bad_conns, columns=['Src', 'Tgt'])
bad['OK'] = False
good = pd.DataFrame(good_conns, columns=['Src', 'Tgt'])
good['OK'] = True
conns = pd.concat([bad, good], ignore_index=True)

In [14]:
conns['Sv'] = conns.Src % 4
conns['Tv'] = conns.Tgt % 4

conns['Sr'] = conns.Sv % 2
conns['Tr'] = conns.Tv % 2

conns['St'] = (conns.Sv // 2) % 2
conns['Tt'] = (conns.Tv // 2) % 2

In [15]:
conns

    Src  Tgt     OK  Sv  Tv  Sr  Tr  St  Tt
0    10    1  False   2   1   0   1   1   0
1    44    6  False   0   2   0   0   0   1
2    46    8  False   2   0   0   0   1   0
3    46   13  False   2   1   0   1   1   0
4    36   15  False   0   3   0   1   0   1
5    50   22  False   2   2   0   0   1   1
6    38   24  False   2   0   0   0   1   0
7    38   27  False   2   3   0   1   1   1
8    42   31  False   2   3   0   1   1   1
9    36   33  False   0   1   0   1   0   0
10   30   40  False   2   0   0   0   1   0
11   34   41  False   2   1   0   1   1   0
12   40   42  False   0   2   0   0   0   1
13   44   44  False   0   0   0   0   0   0
14   48   46  False   0   2   0   0   0   1
15   44   47  False   0   3   0   1   0   1
16   36   49  False   0   1   0   1   0   0
17   49    2   True   1   2   1   0   0   1
18   41    3   True   1   3   1   1   0   1
19   41    4   True   1   0   1   0   0   0
20    9    5   True   1   1   1   1   0   0
21   19    7   True   3   3   1   1   1   1
22    9    9   True   1   1   1   1   0   0
23   25   10   True   1   2   1   0   0   1
24   11   11   True   3   3   1   1   1   1
25   33   12   True   1   0   1   0   0   0
26   37   14   True   1   2   1   0   0   1
27   27   16   True   3   0   1   0   1   0
28   45   17   True   1   1   1   1   0   0
29   29   18   True   1   2   1   0   0   1
30   15   19   True   3   3   1   1   1   1
31   27   20   True   3   0   1   0   1   0
32   21   21   True   1   1   1   1   0   0
33   27   23   True   3   3   1   1   1   1
34    3   25   True   3   1   1   1   1   0
35    5   26   True   1   2   1   0   0   1
36    3   28   True   3   0   1   0   1   0
37   41   29   True   1   1   1   1   0   0
38   49   30   True   1   2   1   0   0   1
39   37   32   True   1   0   1   0   0   0
40   45   34   True   1   2   1   0   0   1
41    5   35   True   1   3   1   1   0   1
42    3   36   True   3   0   1   0   1   0
43   21   37   True   1   1   1   1   0   0
44   29   38   True   1   2   1   0   0   1
45    9   39   True   1   3   1   1   0   1
46   35   43   True   3   3   1   1   1   1
47   41   45   True   1   1   1   1   0   0
48   27   48   True   3   0   1   0   1   0
49   47   50   True   3   2   1   0   1   1

In [24]:
conns.loc[~conns.OK, 'Src':'Tgt'].values.to_list()

AttributeError: 'numpy.ndarray' object has no attribute 'to_list'

In [21]:
conns.loc[~conns.OK, 'Src':'Tgt'].values

array([[10,  1],
       [44,  6],
       [46,  8],
       [46, 13],
       [36, 15],
       [50, 22],
       [38, 24],
       [38, 27],
       [42, 31],
       [36, 33],
       [30, 40],
       [34, 41],
       [40, 42],
       [44, 44],
       [48, 46],
       [44, 47],
       [36, 49]])